/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_com_todd_ndk_NativeUtils */

#ifndef _Included_ua_com_todd_ndk_NativeUtils
#define _Included_ua_com_todd_ndk_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_com_todd_ndk_NativeUtils
 * Method:    nativeMake
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ua_com_todd_ndk_NativeUtils_nativeMake
  (JNIEnv *, jclass);

/*
 * Class:     ua_com_todd_ndk_NativeUtils
 * Method:    nativeDofile
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_ua_com_todd_ndk_NativeUtils_nativeDofile
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ua_com_todd_ndk_NativeUtils
 * Method:    getBuffer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_ua_com_todd_ndk_NativeUtils_getBuffer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
